classes:
  mage:
    max-players:
      value: 20.0
      is-percentage: true
  archer:
    max-players:
      value: 20.0
      is-percentage: true
  knight:
    max-players:
      value: 10.0
      is-percentage: true
  berserk:
    max-players:
      value: 50.0
      is-percentage: true
